cvm-version: 0.7.5
cpus: 2
memory: 8192

containers:
  - name: "test"
    image: "ghcr.io/atlaie/prepilot-vllm-lens:latest@sha256:5f4bee435fb8b6c1be2140acf8f669a4c3a99a5fc5a9234e23223d2f0fe0c268"

shim:
  upstream-port: 8000
  paths:
    - /*
